apiVersion: apps/v1
kind: Deployment
metadata:
  name: senicpos-api
  namespace: senicpos
spec:
  replicas: 3
  selector:
    matchLabels:
      app: senicpos-api
  template:
    metadata:
      labels:
        app: senicpos-api
    spec:
      containers:
      - name: senicpos-api
        image: senicpos-api:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: ASPNETCORE_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: senicpos-api-config
              key: ASPNETCORE_ENVIRONMENT
        - name: UsePostgreSQL
          valueFrom:
            configMapKeyRef:
              name: senicpos-api-config
              key: UsePostgreSQL
        - name: ConnectionStrings__PostgreSQL
          valueFrom:
            secretKeyRef:
              name: senicpos-db-secret
              key: postgres-connection
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: senicpos-api-service
  namespace: senicpos
spec:
  selector:
    app: senicpos-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: senicpos-api-hpa
  namespace: senicpos
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: senicpos-api
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
